### PR TITLE
add acceptance tests for choriaserver

### PR DESCRIPTION
**Pull request by bastelfreak**
Fixes https://github.com/bastelfreak/puppetcontrolrepo/issues/17

### CODE REVIEW

**Comment by bastelfreak** [comment]
```sh
PUPPET_INSTALL_TYPE=agent \
BEAKER_IS_PE=no \
BEAKER_PUPPET_COLLECTION=puppet5 \
BEAKER_debug=true \
BEAKER_setfile=centos7-64{hypervisor=docker\,hostname=puppet.local} \
BEAKER_destroy=no \
bundle exec rspec spec/acceptance/choriaserver_spec.rb
```

fails with

```
An error occurred while loading ./spec/acceptance/choriaserver_spec.rb.
Failure/Error: install_module_from_forge(dependency['name'], dependency['version_requirement'])
Beaker::Host::CommandFailure:
  Host 'puppet.local' exited with 1 running:
   puppet module install choria-choria -v 0.11.1
  Last 10 lines of output were:
  	Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
  	Notice: Downloading from https://forgeapi.puppet.com ...
  	Error: Could not install module 'choria-choria' (???)
  	  No version of 'choria-choria' can satisfy all dependencies
  	    Use `puppet module install --ignore-dependencies` to install only this module
  
# ./.vendor/ruby/2.5.0/gems/beaker-3.37.0/lib/beaker/host.rb:375:in `exec'
# ./.vendor/ruby/2.5.0/gems/beaker-3.37.0/lib/beaker/dsl/helpers/host_helpers.rb:83:in `block in on'
# ./.vendor/ruby/2.5.0/gems/beaker-3.37.0/lib/beaker/shared/host_manager.rb:130:in `run_block_on'
# ./.vendor/ruby/2.5.0/gems/beaker-3.37.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
# ./.vendor/ruby/2.5.0/gems/beaker-3.37.0/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
# ./.vendor/ruby/2.5.0/gems/beaker-puppet-0.17.1/lib/beaker-puppet/install_utils/module_utils.rb:84:in `block in install_puppet_module_via_pmt_on'
# ./.vendor/ruby/2.5.0/gems/beaker-3.37.0/lib/beaker/shared/host_manager.rb:130:in `run_block_on'
# ./.vendor/ruby/2.5.0/gems/beaker-3.37.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
# ./.vendor/ruby/2.5.0/gems/beaker-puppet-0.17.1/lib/beaker-puppet/install_utils/module_utils.rb:62:in `install_puppet_module_via_pmt_on'
# ./.vendor/ruby/2.5.0/gems/beaker-module_install_helper-0.1.7/lib/beaker/module_install_helper.rb:40:in `block (2 levels) in install_module_dependencies_on'
# ./.vendor/ruby/2.5.0/gems/beaker-module_install_helper-0.1.7/lib/beaker/module_install_helper.rb:38:in `each'
# ./.vendor/ruby/2.5.0/gems/beaker-module_install_helper-0.1.7/lib/beaker/module_install_helper.rb:38:in `block in install_module_dependencies_on'
# ./.vendor/ruby/2.5.0/gems/beaker-module_install_helper-0.1.7/lib/beaker/module_install_helper.rb:37:in `each'
# ./.vendor/ruby/2.5.0/gems/beaker-module_install_helper-0.1.7/lib/beaker/module_install_helper.rb:37:in `install_module_dependencies_on'
# ./.vendor/ruby/2.5.0/gems/beaker-module_install_helper-0.1.7/lib/beaker/module_install_helper.rb:61:in `install_module_from_forge_on'
# ./.vendor/ruby/2.5.0/gems/beaker-module_install_helper-0.1.7/lib/beaker/module_install_helper.rb:51:in `install_module_from_forge'
# ./spec/spec_helper_acceptance.rb:17:in `block in <top (required)>'
# ./spec/spec_helper_acceptance.rb:16:in `each'
# ./spec/spec_helper_acceptance.rb:16:in `<top (required)>'
# ./spec/acceptance/choriaserver_spec.rb:2:in `require'
# ./spec/acceptance/choriaserver_spec.rb:2:in `<top (required)>'
No examples found.

Finished in 0.00027 seconds (files took 50.65 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

Installing the module locally works fine:

```
$ puppet module install choria-choria -v 0.11.1
Notice: Preparing to install into /home/bastelfreak/.puppetlabs/etc/code/modules ...
Notice: Created target directory /home/bastelfreak/.puppetlabs/etc/code/modules
Notice: Downloading from https://forgeapi.puppet.com ...
Notice: Installing -- do not interrupt ...
/home/bastelfreak/.puppetlabs/etc/code/modules
└─┬ choria-choria (v0.11.1)
  ├─┬ choria-mcollective_choria (v0.11.0)
  │ ├── choria-mcollective (v0.8.1)
  │ ├── choria-mcollective_agent_filemgr (v2.0.1)
  │ ├── choria-mcollective_agent_package (v5.0.1)
  │ ├── choria-mcollective_agent_puppet (v2.3.1)
  │ ├── choria-mcollective_agent_service (v4.0.1)
  │ └── choria-mcollective_util_actionpolicy (v3.0.0)
  ├─┬ puppetlabs-apt (v6.1.1)
  │ └── puppetlabs-translate (v1.2.0)
  └── puppetlabs-stdlib (v5.1.0)
```

**Comment by scotje** [comment]
@bastelfreak Hmmm, are we sure that forgeapi.puppet.com is resolving to the real forge here? And no others modules are installed in any modulepath?

**Comment by bastelfreak** [comment]
```
$ PUPPET_INSTALL_TYPE=agent BEAKER_IS_PE=no BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=centos7-64{hypervisor=docker\,hostname=puppet.local} BEAKER_destroy=no bundle exec rspec spec/acceptance/choriaserver_spec.rb 
/home/bastelfreak/puppetcontrolrepo/modules/profiles/.vendor/ruby/2.5.0/gems/beaker-rspec-6.2.4/lib/beaker-rspec/helpers/serverspec.rb:43: warning: already initialized constant Module::VALID_OPTIONS_KEYS
/home/bastelfreak/puppetcontrolrepo/modules/profiles/.vendor/ruby/2.5.0/gems/specinfra-2.76.2/lib/specinfra/configuration.rb:4: warning: previous definition of VALID_OPTIONS_KEYS was here

Hosts file 'centos7-64{hypervisor=docker,hostname=puppet.local}' does not exist.
Trying as beaker-hostgenerator input.

Hypervisor for puppet.local is docker
Beaker::Hypervisor, found some docker boxes to create
get
/v1.16/version
{}

Provisioning docker
provisioning puppet.local
Creating image
Dockerfile is           FROM centos:7
          ENV container docker
            RUN yum clean all
            RUN yum install -y sudo openssh-server openssh-clients curl ntpdate
            RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key
            RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key
          RUN mkdir -p /var/run/sshd
          RUN echo root:root | chpasswd
          RUN sed -ri 's/^#?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
          RUN sed -ri 's/^#?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
          RUN sed -ri 's/^#?UseDNS .*/UseDNS no/' /etc/ssh/sshd_config
RUN systemctl mask getty@tty1.service
RUN yum install -y crontabs initscripts iproute openssl sysvinit-tools tar wget which ss
          EXPOSE 22
          CMD ["/sbin/init"]
Docker build buildargs: {}
post
/v1.16/build
{:rm=>true, :buildargs=>"{}"}
Dockerfile0000640000000000000000000000145113372641222013307 0ustar00wheelwheel00000000000000          FROM centos:7
          ENV container docker
            RUN yum clean all
            RUN yum install -y sudo openssh-server openssh-clients curl ntpdate
            RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key
            RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key
          RUN mkdir -p /var/run/sshd
          RUN echo root:root | chpasswd
          RUN sed -ri 's/^#?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
          RUN sed -ri 's/^#?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
          RUN sed -ri 's/^#?UseDNS .*/UseDNS no/' /etc/ssh/sshd_config
RUN systemctl mask getty@tty1.service
RUN yum install -y crontabs initscripts iproute openssl sysvinit-tools tar wget which ss
          EXPOSE 22
          CMD ["/sbin/init"]

Creating container from image 95356e8140e7
post
/v1.16/containers/create
{}
{"Image":"95356e8140e7","Hostname":"puppet.local","HostConfig":{"PortBindings":{"22/tcp":[{"HostPort":"0989","HostIp":"0.0.0.0"}]},"PublishAllPorts":true,"Privileged":true,"RestartPolicy":{"Name":"always"}}}
Starting container 59a857ee29ff7025c612f13cf5e9f71255f9ce096fca3043a7c2bfab9d8bd9cb
post
/v1.16/containers/59a857ee29ff7025c612f13cf5e9f71255f9ce096fca3043a7c2bfab9d8bd9cb/start
{}
{}
Using docker server at 62.138.188.26
get
/v1.16/containers/59a857ee29ff7025c612f13cf5e9f71255f9ce096fca3043a7c2bfab9d8bd9cb/json
{}

node available as  ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@62.138.188.26 -p 989
get
/v1.16/containers/59a857ee29ff7025c612f13cf5e9f71255f9ce096fca3043a7c2bfab9d8bd9cb/json
{}


puppet.local 22:30:59$ cat /etc/resolv.conf
  Attempting ssh connection to 62.138.188.26, user: root, opts: {:password=>"root", :port=>"989", :forward_agent=>false}
  Warning: Try 1 -- Host 62.138.188.26 unreachable: Errno::ECONNREFUSED - Connection refused - connect(2) for 62.138.188.26:989
  Warning: Trying again in 3 seconds
  Attempting ssh connection to 62.138.188.26, user: root, opts: {:password=>"root", :port=>"989", :forward_agent=>false, :logger=>#<Logger:0x0000561c2eec94b0 @level=4, @progname=nil, @default_formatter=#<Logger::Formatter:0x0000561c2eec93e8 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x0000561c2eec92f8 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDERR>>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x0000561c2eec9280>>>, :password_prompt=>#<Net::SSH::Prompt:0x0000561c2eec9258>, :user=>"root"}
  # This file is managed by man:systemd-resolved(8). Do not edit.
  #
  # This is a dynamic resolv.conf file for connecting local clients directly to
  # all known uplink DNS servers. This file lists all configured search domains.
  #
  # Third party programs must not access this file directly, but only through the
  # symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
  # replace this symlink by a static file or a different symlink.
  #
  # See man:systemd-resolved.service(8) for details about the supported modes of
  # operation for /etc/resolv.conf.
  
  nameserver 80.237.128.144
  # Too many DNS servers configured, the following entries may be ignored.
  nameserver 80.237.128.145
  search cloud.fabric.mass.systems

puppet.local executed in 3.59 seconds

puppet.local 22:31:03$ echo '127.0.0.1	localhost localhost.localdomain
172.17.0.8	puppet.local.cloud.fabric.mass.systems puppet.local
' >> /etc/hosts

puppet.local executed in 0.14 seconds

puppet.local 22:31:03$ rpm -q curl
  curl-7.29.0-46.el7.x86_64

puppet.local executed in 0.18 seconds

puppet.local 22:31:03$ rpm -q ntpdate
  ntpdate-4.2.6p5-28.el7.centos.x86_64

puppet.local executed in 0.17 seconds
setting local environment on puppet.local

puppet.local 22:31:03$ getent passwd root
  root:x:0:0:root:/root:/bin/bash

puppet.local executed in 0.14 seconds

puppet.local 22:31:03$ mktemp -dt .XXXXXX
  /tmp/.d4zaAr

puppet.local executed in 0.14 seconds

puppet.local 22:31:03$ chown root:root /tmp/.d4zaAr

puppet.local executed in 0.14 seconds

puppet.local 22:31:04$ echo 'PermitUserEnvironment yes' | cat - /etc/ssh/sshd_config > /tmp/.d4zaAr/sshd_config.permit

puppet.local executed in 0.14 seconds

puppet.local 22:31:04$ mv /tmp/.d4zaAr/sshd_config.permit /etc/ssh/sshd_config

puppet.local executed in 0.14 seconds

puppet.local 22:31:04$ systemctl restart sshd.service

puppet.local executed in 0.16 seconds

puppet.local 22:31:04$ mkdir -p ~/.ssh

puppet.local executed in 0.15 seconds

puppet.local 22:31:04$ chmod 0600 ~/.ssh

puppet.local executed in 0.14 seconds

puppet.local 22:31:04$ touch ~/.ssh/environment

puppet.local executed in 0.14 seconds

puppet.local 22:31:04$ grep ^PATH=.*\$PATH ~/.ssh/environment

puppet.local executed in 0.14 seconds
Exited: 1

puppet.local 22:31:05$ grep ^PATH= ~/.ssh/environment

puppet.local executed in 0.14 seconds
Exited: 1

puppet.local 22:31:05$ echo "PATH=$PATH" >> ~/.ssh/environment

puppet.local executed in 0.14 seconds
will not mirror environment to /etc/profile.d on non-sles/debian platform host

puppet.local 22:31:05$ echo "/usr/bin"
  /usr/bin

puppet.local executed in 0.14 seconds

puppet.local 22:31:05$ echo "/opt/puppet-git-repos/hiera/bin"
  /opt/puppet-git-repos/hiera/bin

puppet.local executed in 0.14 seconds

puppet.local 22:31:05$ grep ^PATH=.*\/usr\/bin:\/opt\/puppet\-git\-repos\/hiera\/bin ~/.ssh/environment

puppet.local executed in 0.14 seconds
Exited: 1

puppet.local 22:31:05$ grep ^PATH= ~/.ssh/environment
  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin

puppet.local executed in 0.14 seconds

puppet.local 22:31:05$ sed -i -e "s/^PATH=/PATH=\/usr\/bin:\/opt\/puppet\-git\-repos\/hiera\/bin:/" ~/.ssh/environment

puppet.local executed in 0.14 seconds
will not mirror environment to /etc/profile.d on non-sles/debian platform host

puppet.local 22:31:06$ grep ^PATH=.*PATH ~/.ssh/environment

puppet.local executed in 0.14 seconds
Exited: 1

puppet.local 22:31:06$ grep ^PATH= ~/.ssh/environment
  PATH=/usr/bin:/opt/puppet-git-repos/hiera/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin

puppet.local executed in 0.15 seconds

puppet.local 22:31:06$ sed -i -e "s/^PATH=/PATH=PATH:/" ~/.ssh/environment

puppet.local executed in 0.14 seconds
will not mirror environment to /etc/profile.d on non-sles/debian platform host
ssh connection to puppet.local has been terminated

puppet.local 22:31:06$ cat ~/.ssh/environment
  Attempting ssh connection to 62.138.188.26, user: root, opts: {:password=>"root", :port=>"989", :forward_agent=>false, :logger=>#<Logger:0x0000561c2eec94b0 @level=4, @progname=nil, @default_formatter=#<Logger::Formatter:0x0000561c2eec93e8 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x0000561c2eec92f8 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDERR>>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x0000561c2eec9280>>>, :password_prompt=>#<Net::SSH::Prompt:0x0000561c2eec9258>, :user=>"root"}
  PATH=PATH:/usr/bin:/opt/puppet-git-repos/hiera/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin

puppet.local executed in 0.56 seconds
Disabling updates.puppetlabs.com by modifying hosts file to resolve updates to 127.0.0.1 on puppet.local

puppet.local 22:31:07$ echo '127.0.0.1	updates.puppetlabs.com
' >> /etc/hosts

puppet.local executed in 0.14 seconds

puppet.local 22:31:07$ rpm --replacepkgs -Uvh http://yum.puppetlabs.com/puppet6/puppet6-release-el-7.noarch.rpm 
  warning: /var/tmp/rpm-tmp.nAQULZ: Header V4 RSA/SHA256 Signature, key ID ef8d349f: NOKEY
  Retrieving http://yum.puppetlabs.com/puppet6/puppet6-release-el-7.noarch.rpm
  Preparing...                            ########################################
  Updating / installing...
  puppet6-release-6.0.0-1.el7             ##########################  #######  ##  ###  ##

puppet.local executed in 1.25 seconds

puppet.local 22:31:08$ echo "/opt/puppetlabs/bin"
  /opt/puppetlabs/bin

puppet.local executed in 0.14 seconds

puppet.local 22:31:08$ echo "/opt/puppet-git-repos/hiera/bin"
  /opt/puppet-git-repos/hiera/bin

puppet.local executed in 0.14 seconds

puppet.local 22:31:08$ grep ^PATH=.*\/opt\/puppetlabs\/bin:\/opt\/puppet\-git\-repos\/hiera\/bin ~/.ssh/environment

puppet.local executed in 0.14 seconds
Exited: 1

puppet.local 22:31:08$ grep ^PATH= ~/.ssh/environment
  PATH=PATH:/usr/bin:/opt/puppet-git-repos/hiera/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin

puppet.local executed in 0.14 seconds

puppet.local 22:31:09$ sed -i -e "s/^PATH=/PATH=\/opt\/puppetlabs\/bin:\/opt\/puppet\-git\-repos\/hiera\/bin:/" ~/.ssh/environment

puppet.local executed in 0.15 seconds
will not mirror environment to /etc/profile.d on non-sles/debian platform host

puppet.local 22:31:09$ grep ^PATH=.*PATH ~/.ssh/environment
  PATH=/opt/puppetlabs/bin:/opt/puppet-git-repos/hiera/bin:PATH:/usr/bin:/opt/puppet-git-repos/hiera/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin

puppet.local executed in 0.14 seconds

puppet.local 22:31:09$ yum -y  install puppet-agent
  Loaded plugins: fastestmirror, ovl
  Loading mirror speeds from cached hostfile
   * base: mirror.infonline.de
   * extras: mirror.infonline.de
   * updates: centos.intergenia.de
  Resolving Dependencies
  --> Running transaction check
  ---> Package puppet-agent.x86_64 0:6.0.4-1.el7 will be installed
  --> Finished Dependency Resolution
  
  Dependencies Resolved
  
  ================================================================================
   Package              Arch           Version              Repository       Size
  ================================================================================
  Installing:
   puppet-agent         x86_64         6.0.4-1.el7          puppet6          21 M
  
  Transaction Summary
  ================================================================================
  Install  1 Package
  Total download size: 21 M
  Installed size: 90 M
  Downloading packages:
  warning: /var/cache/yum/x86_64/7/puppet6/packages/puppet-agent-6.0.4-1.el7.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID ef8d349f: NOKEY
  Public key for puppet-agent-6.0.4-1.el7.x86_64.rpm is not installed
  Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-puppet6-release
  Importing GPG key 0xEF8D349F:
   Userid     : "Puppet, Inc. Release Key (Puppet, Inc. Release Key) <release@puppet.com>"
   Fingerprint: 6f6b 1550 9cf8 e59e 6e46 9f32 7f43 8280 ef8d 349f
   Package    : puppet6-release-6.0.0-1.el7.noarch (installed)
   From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-puppet6-release
  Running transaction check
  Running transaction test
  Transaction test succeeded
  Running transaction
  Warning: RPMDB altered outside of yum.
    Installing : puppet-agent-6.0.4-1.el7.x86_64                              1/1   
    Verifying  : puppet-agent-6.0.4-1.el7.x86_64                              1/1   
  
  Installed:
    puppet-agent.x86_64 0:6.0.4-1.el7                                             
  Complete!

puppet.local executed in 7.86 seconds

puppet.local 22:31:17$ echo "/opt/puppetlabs/bin"
  /opt/puppetlabs/bin

puppet.local executed in 0.14 seconds

puppet.local 22:31:17$ echo "/opt/puppet-git-repos/hiera/bin"
  /opt/puppet-git-repos/hiera/bin

puppet.local executed in 0.14 seconds

puppet.local 22:31:17$ grep ^PATH=.*\/opt\/puppetlabs\/bin:\/opt\/puppet\-git\-repos\/hiera\/bin ~/.ssh/environment
  PATH=/opt/puppetlabs/bin:/opt/puppet-git-repos/hiera/bin:PATH:/usr/bin:/opt/puppet-git-repos/hiera/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin

puppet.local executed in 0.15 seconds

puppet.local 22:31:17$ grep ^PATH=.*PATH ~/.ssh/environment
  PATH=/opt/puppetlabs/bin:/opt/puppet-git-repos/hiera/bin:PATH:/usr/bin:/opt/puppet-git-repos/hiera/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin

puppet.local executed in 0.14 seconds

puppet.local 22:31:17$ echo /etc/puppetlabs/code/modules
  /etc/puppetlabs/code/modules

puppet.local executed in 0.14 seconds
Using scp to transfer /home/bastelfreak/puppetcontrolrepo/modules/profiles to /etc/puppetlabs/code/modules/profiles
localhost $ scp /home/bastelfreak/puppetcontrolrepo/modules/profiles puppet.local:/etc/puppetlabs/code/modules {:ignore => [".bundle", ".git", ".idea", ".vagrant", ".vendor", "vendor", "acceptance", "bundle", "spec", "tests", "log", ".svn", "junit", "pkg", "example", ".", ".."]}
going to ignore (?-mix:((\/|\A)\.bundle(\/|\z))|((\/|\A)\.git(\/|\z))|((\/|\A)\.idea(\/|\z))|((\/|\A)\.vagrant(\/|\z))|((\/|\A)\.vendor(\/|\z))|((\/|\A)vendor(\/|\z))|((\/|\A)acceptance(\/|\z))|((\/|\A)bundle(\/|\z))|((\/|\A)spec(\/|\z))|((\/|\A)tests(\/|\z))|((\/|\A)log(\/|\z))|((\/|\A)\.svn(\/|\z))|((\/|\A)junit(\/|\z))|((\/|\A)pkg(\/|\z))|((\/|\A)example(\/|\z))|((\/|\A)\.(\/|\z))|((\/|\A)\.\.(\/|\z)))

puppet.local 22:31:23$ puppet module install choria-choria -v 0.11.1
  Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
  Notice: Downloading from https://forgeapi.puppet.com ...
  Error: Could not install module 'choria-choria' (???)
    No version of 'choria-choria' can satisfy all dependencies
      Use `puppet module install --ignore-dependencies` to install only this module

puppet.local executed in 25.15 seconds
Exited: 1

An error occurred while loading ./spec/acceptance/choriaserver_spec.rb.
Failure/Error: install_module_from_forge(dependency['name'], dependency['version_requirement'])
Beaker::Host::CommandFailure:
  Host 'puppet.local' exited with 1 running:
   puppet module install choria-choria -v 0.11.1
  Last 10 lines of output were:
  	Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
  	Notice: Downloading from https://forgeapi.puppet.com ...
  	Error: Could not install module 'choria-choria' (???)
  	  No version of 'choria-choria' can satisfy all dependencies
  	    Use `puppet module install --ignore-dependencies` to install only this module
  
# ./.vendor/ruby/2.5.0/gems/beaker-3.37.0/lib/beaker/host.rb:375:in `exec'
# ./.vendor/ruby/2.5.0/gems/beaker-3.37.0/lib/beaker/dsl/helpers/host_helpers.rb:83:in `block in on'
# ./.vendor/ruby/2.5.0/gems/beaker-3.37.0/lib/beaker/shared/host_manager.rb:130:in `run_block_on'
# ./.vendor/ruby/2.5.0/gems/beaker-3.37.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
# ./.vendor/ruby/2.5.0/gems/beaker-3.37.0/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
# ./.vendor/ruby/2.5.0/gems/beaker-puppet-0.17.1/lib/beaker-puppet/install_utils/module_utils.rb:84:in `block in install_puppet_module_via_pmt_on'
# ./.vendor/ruby/2.5.0/gems/beaker-3.37.0/lib/beaker/shared/host_manager.rb:130:in `run_block_on'
# ./.vendor/ruby/2.5.0/gems/beaker-3.37.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
# ./.vendor/ruby/2.5.0/gems/beaker-puppet-0.17.1/lib/beaker-puppet/install_utils/module_utils.rb:62:in `install_puppet_module_via_pmt_on'
# ./.vendor/ruby/2.5.0/gems/beaker-module_install_helper-0.1.7/lib/beaker/module_install_helper.rb:40:in `block (2 levels) in install_module_dependencies_on'
# ./.vendor/ruby/2.5.0/gems/beaker-module_install_helper-0.1.7/lib/beaker/module_install_helper.rb:38:in `each'
# ./.vendor/ruby/2.5.0/gems/beaker-module_install_helper-0.1.7/lib/beaker/module_install_helper.rb:38:in `block in install_module_dependencies_on'
# ./.vendor/ruby/2.5.0/gems/beaker-module_install_helper-0.1.7/lib/beaker/module_install_helper.rb:37:in `each'
# ./.vendor/ruby/2.5.0/gems/beaker-module_install_helper-0.1.7/lib/beaker/module_install_helper.rb:37:in `install_module_dependencies_on'
# ./.vendor/ruby/2.5.0/gems/beaker-module_install_helper-0.1.7/lib/beaker/module_install_helper.rb:61:in `install_module_from_forge_on'
# ./.vendor/ruby/2.5.0/gems/beaker-module_install_helper-0.1.7/lib/beaker/module_install_helper.rb:51:in `install_module_from_forge'
# ./spec/spec_helper_acceptance.rb:17:in `block in <top (required)>'
# ./spec/spec_helper_acceptance.rb:16:in `each'
# ./spec/spec_helper_acceptance.rb:16:in `<top (required)>'
# ./spec/acceptance/choriaserver_spec.rb:2:in `require'
# ./spec/acceptance/choriaserver_spec.rb:2:in `<top (required)>'
No examples found.

Finished in 0.00027 seconds (files took 51.47 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

**Comment by bastelfreak** [comment]
Hi @scotje. I added the full beaker output. I saw those errors in the past when a dependency pulled in stdlib 5.X and the next module that beaker tries to install only supports stdlib 4.x. In this case, `choria-choria` seems to be the first module that gets installed, so I'm a bit confused.

**Comment by bastelfreak** [comment]
ohhhhhhh software....
I had a type in the metadata.json in this profile module:

```patch
diff --git a/modules/profiles/metadata.json b/modules/profiles/metadata.json
index b335522..cdea9d3 100644
--- a/modules/profiles/metadata.json
+++ b/modules/profiles/metadata.json
@@ -78,7 +78,7 @@
     },
     {
       "name": "choria/mcollective_agent_filemgr",
-      "version_requirement": ">= 4.0.1 < 5.0.0"
+      "version_requirement": ">= 2.0.1 < 3.0.0"
     },
     {
       "name": "choria/mcollective_agent_nettest",
```

**Comment by bastelfreak** [comment]
the requried `beaker-hiera` patch to work with puppet5:

```patch
$ git diff --no-index .vendor/ruby/2.5.0/gems/beaker-hiera-0.1.1/lib/beaker-hiera/helpers.rb /tmp/helper.rb
diff --git a/.vendor/ruby/2.5.0/gems/beaker-hiera-0.1.1/lib/beaker-hiera/helpers.rb b/tmp/helper.rb
index d5b6945..e53a6bf 100644
--- a/.vendor/ruby/2.5.0/gems/beaker-hiera-0.1.1/lib/beaker-hiera/helpers.rb
+++ b/tmp/helper.rb
@@ -16,8 +16,7 @@ module Beaker
             hiera_config=Hash.new
             hiera_config[:backends] = 'yaml'
             hiera_config[:yaml] = {}
-            #hiera_config[:yaml][:datadir] = hiera_datadir(host)
-            hiera_config[:yaml][:datadir] = '/etc/puppetlabs/puppet/hieradata/'
+            hiera_config[:yaml][:datadir] = hiera_datadir(host)
             hiera_config[:hierarchy] = hierarchy
             hiera_config[:logger] = 'console'
             create_remote_file host, host.puppet['hiera_config'], hiera_config.to_yaml
@@ -52,8 +51,7 @@ module Beaker
         #
         # @return [String] Path to the hiera data directory
         def hiera_datadir(host)
-          #host[:type] =~ /aio/ ? File.join(host.puppet['codedir'], 'hieradata') : host[:hieradatadir]
-          '/etc/puppetlabs/puppet/'
+          host[:type] =~ /aio/ ? File.join(host.puppet['codedir'], 'hieradata') : host[:hieradatadir]
         end
 
       end
```

**Comment by bastelfreak** [comment]
Right now it works on CentOS 7 but fails on Ubuntu18.04:

```
Failures:

  1) profiles::choriaserver class default parameters works idempotently with no errors
     Failure/Error: apply_manifest(pp, catch_failures: true)
     Beaker::Host::CommandFailure:
       Host 'puppet.local' exited with 6 running:
        puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.cg0NMS
       Last 10 lines of output were:
       	Info: /Stage[main]/Choria::Config/File[/etc/choria/server.conf]: Scheduling refresh of Class[Choria::Service]
       	Info: /Stage[main]/Choria::Config/File[/etc/choria/server.conf]: Scheduling refresh of Class[Choria::Service]
       	Info: Class[Choria::Service]: Scheduling refresh of Service[choria-server]
       	Notice: /Stage[main]/Choria::Service/Service[choria-server]/ensure: ensure changed 'stopped' to 'running'
       	Info: /Stage[main]/Choria::Service/Service[choria-server]: Unscheduling refresh on Service[choria-server]
       	Info: Class[Mcollective::Facts]: Unscheduling all events on Class[Mcollective::Facts]
       	Info: Stage[main]: Unscheduling all events on Stage[main]
       	Error: Could not find a suitable provider for cron
       	Info: Creating state file /opt/puppetlabs/puppet/cache/state/state.yaml
       	Notice: Applied catalog in 50.60 seconds
       
     # ./.vendor/ruby/2.5.0/gems/beaker-3.37.0/lib/beaker/host.rb:375:in `exec'
     # ./.vendor/ruby/2.5.0/gems/beaker-3.37.0/lib/beaker/dsl/helpers/host_helpers.rb:83:in `block in on'
     # ./.vendor/ruby/2.5.0/gems/beaker-3.37.0/lib/beaker/shared/host_manager.rb:130:in `run_block_on'
     # ./.vendor/ruby/2.5.0/gems/beaker-3.37.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
     # ./.vendor/ruby/2.5.0/gems/beaker-3.37.0/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
     # ./.vendor/ruby/2.5.0/gems/beaker-puppet-0.17.1/lib/beaker-puppet/helpers/puppet_helpers.rb:521:in `block in apply_manifest_on'
     # ./.vendor/ruby/2.5.0/gems/beaker-3.37.0/lib/beaker/shared/host_manager.rb:130:in `run_block_on'
     # ./.vendor/ruby/2.5.0/gems/beaker-3.37.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
     # ./.vendor/ruby/2.5.0/gems/beaker-puppet-0.17.1/lib/beaker-puppet/helpers/puppet_helpers.rb:450:in `apply_manifest_on'
     # ./.vendor/ruby/2.5.0/gems/beaker-puppet-0.17.1/lib/beaker-puppet/helpers/puppet_helpers.rb:528:in `apply_manifest'
     # ./spec/acceptance/choriaserver_spec.rb:19:in `block (3 levels) in <top (required)>'

Finished in 1 minute 0.04 seconds (files took 4 minutes 47.7 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/acceptance/choriaserver_spec.rb:13 # profiles::choriaserver class default parameters works idempotently with no errors
```

**Comment by bastelfreak** [comment]
The basic acceptance test works on:
* CentOS 7
* Ubuntu 16.04
* Ubuntu 18.04
* Debian 9

**Pull request merged**
